readWD: readWD.cpp File Reference
readWD.cpp File Reference
#include <curses.h>
#include <fstream>
#include <iostream>
#include <cstring>
#include <stdio.h>
#include <vector>
#include <TF1.h>
#include <TFile.h>
#include <TGraph.h>
#include <TH1F.h>
#include <TMath.h>
#include <TString.h>
#include <TSystem.h>
#include <TTree.h>
#include <TMatrixD.h>
#include <TVectorD.h>
Classes
struct FileHeader
File header.
struct EventHeader
Event header.
struct IntegrationWindow
Integration window.
struct Configuration
Configuration struct.
Macros
#define __READ_VERSION__ "0.9.4 Beta (22.06.2020)"
#define Debug
#define DEBUG
#define SAMPLES_PER_WAVEFORM 1024
Functions
std::ifstream * Initialise (std::string)
int GetIntegrationBounds (std::ifstream *file)
Get the Integration Bounds object.
int ReadAnEvent (std::ifstream *file, EventHeader &eh, std::vector< float * > &wfData, std::vector< unsigned short > *tCell)
Reads an event.
int ReadFile (std::ifstream *file)
Read the whole file.
int Config ()
void PrintHelp ()
void subtractSineNoise (float *wfData, float *wfTime, float &ampl, float &phi, char *name=0)
Subtract sine noise from waveform.
void getPedestal (float *aWaveform, float &pedestal, float &stdv)
Determines mean and standard deviation of pedestal.
void getPedestal (TH1F *hSignal, float &pedestal, float &stdv)
Determines mean and standard deviation of pedestal.
float getTimeStamp (EventHeader eh)
Get the timestamp.
int main (int argc, const char **argv)
Variables
Configuration gCONFIG
Macro Definition Documentation
__READ_VERSION__
#define __READ_VERSION__ "0.9.4 Beta (22.06.2020)"
Definition at line 33 of file readWD.cpp.
Debug
#define Debug
Value:
    if (gCONFIG.debug) \
    std::cout << "DEBUG L" << __LINE__ << ": "
Definition at line 208 of file readWD.cpp.
DEBUG
#define DEBUG
Value:
    if (gCONFIG.debug > 1) \
    std::cout << "DEBUG L" << __LINE__ << ": "
Definition at line 211 of file readWD.cpp.
SAMPLES_PER_WAVEFORM
#define SAMPLES_PER_WAVEFORM 1024
Definition at line 214 of file readWD.cpp.
Function Documentation
Config()
int Config ()
Returns
int
Definition at line 1143 of file readWD.cpp.
References __READ_VERSION__, Configuration::cfFraction, Configuration::debug, gCONFIG, Configuration::intDecay, Configuration::intRise, Configuration::leThreshold, Configuration::noiseFrequency, Configuration::nSampleEvents, Configuration::nSaveEvents, Configuration::sigWF, and Configuration::subtractSine.
Referenced by main().
GetIntegrationBounds()
int GetIntegrationBounds (std::ifstream * file)
Get the Integration Bounds object.
Parameters
file
Returns
int
Definition at line 692 of file readWD.cpp.
References Debug, gCONFIG, getPedestal(), Configuration::intDecay, Configuration::integrationWindows, Configuration::intRise, Configuration::nChannelsPerBoard, Configuration::nSampleEvents, ReadAnEvent(), SAMPLES_PER_WAVEFORM, IntegrationWindow::start, IntegrationWindow::stop, and Configuration::theFile.
Referenced by main().
getPedestal() [1/2]
void getPedestal (float * aWaveform, float & pedestal, float & stdv)
Determines mean and standard deviation of pedestal.
Determine standard deviation of the first 100 samples and the second 100 samples. The range with the smaller standard deviation will be used to determine the pedestal for the waveform.
Parameters
aWaveform
pedestal
stdv
Definition at line 241 of file readWD.cpp.
Referenced by GetIntegrationBounds(), and ReadFile().
getPedestal() [2/2]
void getPedestal (TH1F * hSignal, float & pedestal, float & stdv)
Determines mean and standard deviation of pedestal.
Determine standard deviation of the first 100 samples and the second 100 samples. The range with the smaller standard deviation will be used to determine the pedestal for the waveform.
Parameters
hSignal
pedestal
stdv
Definition at line 269 of file readWD.cpp.
getTimeStamp()
float getTimeStamp (EventHeader eh)
Get the timestamp.
Get the timestamp from the event header.
Parameters
eh The event header
Returns
Returns the timestamp
Definition at line 367 of file readWD.cpp.
References EventHeader::day, EventHeader::hour, EventHeader::min, EventHeader::ms, EventHeader::sec, and EventHeader::serialNumber.
Referenced by ReadFile().
Initialise()
std::ifstream * Initialise (std::string filename)
Parameters
filename
Returns
std::ifstream*
Definition at line 541 of file readWD.cpp.
References Debug, Configuration::firstOfRun, gCONFIG, Configuration::integrationWindows, Configuration::nChannelsPerBoard, Configuration::runMode, SAMPLES_PER_WAVEFORM, FileHeader::tag, EventHeader::tag, Configuration::timeBinWidth, and FileHeader::version.
Referenced by main().
main()
int main (int argc, const char ** argv)
Parameters
argc
argv
Returns
int
Definition at line 1446 of file readWD.cpp.
References __READ_VERSION__, Config(), Configuration::debug, Debug, gCONFIG, GetIntegrationBounds(), Initialise(), Configuration::nSampleEvents, PrintHelp(), ReadFile(), Configuration::run, Configuration::sigWF, Configuration::subtractSine, Configuration::theFile, and Configuration::timeBinWidth.
PrintHelp()
void PrintHelp ()
Definition at line 1421 of file readWD.cpp.
Referenced by main().
ReadAnEvent()
int ReadAnEvent (std::ifstream * file, EventHeader & eh, std::vector< float * > & wfData, std::vector< unsigned short > * tCell)
Reads an event.
Reads an event in parallel from any channel available.
Parameters
file Input file, opened with Initialise() and the current position at the beginning of the EHDR
eh Event header at which the event will be read
wfData Waveform data at which the waveform data will be read
tCell Trigger cell
Returns
0 on success, 1 for EOF, 2 otherwise
Definition at line 396 of file readWD.cpp.
References DEBUG, Configuration::firstOfRun, gCONFIG, Configuration::nChannelsPerBoard, EventHeader::rangeCenter, Configuration::runMode, SAMPLES_PER_WAVEFORM, EventHeader::serialNumber, and EventHeader::tag.
Referenced by GetIntegrationBounds(), and ReadFile().
ReadFile()
int ReadFile (std::ifstream * file)
Read the whole file.
Read the whole .dat file and write the values to a tree. The tree gets saved to the file gCONFIG.theFile.
Parameters
file Opened .dat file. The current position is at the first event header.
Returns
0 on success, 1 otherwise
< The value to be returned
Definition at line 835 of file readWD.cpp.
References Configuration::cfFraction, Configuration::debug, Debug, DEBUG, gCONFIG, getPedestal(), getTimeStamp(), Configuration::integrationWindows, Configuration::leThreshold, Configuration::nChannelsPerBoard, Configuration::nSaveEvents, ReadAnEvent(), Configuration::run, SAMPLES_PER_WAVEFORM, EventHeader::serialNumber, Configuration::sigWF, IntegrationWindow::start, IntegrationWindow::stop, Configuration::subtractSine, subtractSineNoise(), Configuration::theFile, and Configuration::timeBinWidth.
Referenced by main().
subtractSineNoise()
void subtractSineNoise (float * wfData, float * wfTime, float & ampl, float & phi, char * name = 0)
Subtract sine noise from waveform.
Subtract sine noise from waveform. To be further understood.
Parameters
wfData
wfTime
ampl
phi
name
Definition at line 316 of file readWD.cpp.
References gCONFIG, Configuration::noiseFrequency, and SAMPLES_PER_WAVEFORM.
Referenced by ReadFile().
Variable Documentation
gCONFIG
Configuration gCONFIG
Definition at line 207 of file readWD.cpp.
Referenced by Config(), GetIntegrationBounds(), Initialise(), main(), ReadAnEvent(), ReadFile(), and subtractSineNoise().